version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: 
          name: Install Yarn Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      # Lint Theme
      - run: yarn lint
      # Build Theme into .Zip
      - run: yarn zip
      # Move Theme Zip into Artifacts
      - run: 
          name: Move Theme Zip into Artifacts
          command: |
            mkdir export
            cp starter-theme.zip export/theme.zip
      # Upload to Netlify & Deploy (Public Url for Shopify to Fetch Theme)
      - run: 
          name: Upload Theme.zip to Netlify
          command: ./node_modules/.bin/netlify deploy --dir=export --auth=${NETLIFY_AUTH_TOKEN} --site=${NETLIFY_SITE_ID} --prod
      # Upload Theme to Shopify
      - run:
          name: Upload Theme to Shopify
          command: .circleci/theme-upload.js
      # List Shopify Themes
      - run: yarn list-themes
      # Continously Check for Preview Available
      - run: 
          name: Check If Theme is Previewable
          command: .circleci/theme-check.js
      # Begin Fulls-site QA (Add as a new Job)

      