name: Shopify CI/CD
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build + Deploy Preview
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x

    - name: Use Yarn 1.17.2
      run: |
        npm install -g yarn@1.17.2
        yarn

    - name: Lint Theme Locales
      run: |
        npm i -g @shopify/theme-lint
        theme-lint ./src

    - name: Lint Theme Config Files
      run: |
        npm i -g jsonlint-tree
        jsonlint-tree src/config
        
    # - name: TODO: Lint Theme JS
    #   run: yarn lint
    
    # - name: TODO: Lint Theme Styles
    #   run: yarn theme-styles

    # Copy down staging src/config/settings_data.json ?
        
    - name: Zip Theme
      run: node .github/workflows/scripts/theme-zip.js

    - name: Delete existing PR Theme
      run: node .github/workflows/scripts/theme-delete.js 
      env:
        SHOP_NAME: ${{secrets.SHOP_NAME}}
        API_KEY: ${{secrets.API_KEY}}
        API_PASSWORD: ${{secrets.API_PASSWORD}}
        GITHUB_REPOSITORY: ${{secrets.GITHUB_REPOSITORY}}
        GITHUB_EVENT_PATH: ${{secrets.GITHUB_EVENT_PATH}}
        GITHUB_SHA: ${{secrets.GITHUB_SHA}}

    - name: Upload Theme to Shopify
      run: |
        node .github/workflows/scripts/theme-upload.js
        node .github/workflows/scripts/theme-check.js
      env:
        SHOP_NAME: ${{secrets.SHOP_NAME}}
        API_KEY: ${{secrets.API_KEY}}
        API_PASSWORD: ${{secrets.API_PASSWORD}}
        NGROK_AUTH_TOKEN: ${{secrets.NGROK_AUTH_TOKEN}}
        GITHUB_REPOSITORY: ${{secrets.GITHUB_REPOSITORY}}
        GITHUB_EVENT_PATH: ${{secrets.GITHUB_EVENT_PATH}}
        GITHUB_SHA: ${{secrets.GITHUB_SHA}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}